plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.jobrunr'
version = '0.0.1-SNAPSHOT'
description = 'spring-app'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.jobrunr:jobrunr-spring-boot-4-starter:9.0.0'

    testImplementation 'org.jobrunr:jobrunr:9.0.0:test-fixtures'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
